### ISSUE TITLE
When loading ModifyTraining.dart (Unexpected Null Value)

### ISSUE THREAD

**Issue by spartanathlete** [THE-TEAM-com-tn/kadhem-repo#2]
[+161075 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[ +115 ms] The following TypeErrorImpl was thrown building _FormScope:
[   +1 ms] Unexpected null value.
[   +1 ms] The relevant error-causing widget was:
[        ]   Form-[LabeledGlobalKey<FormState>#927f8]
[        ]
lib\…\trainings\modify_training_page.dart:170
[   +2 ms] When the exception was thrown, this was the stack:
[   +1 ms] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
[   +3 ms] C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 561:63  nullCheck
[   +4 ms] packages/team_elearny/trainings_management_section/ui/shared/input_widget.dart 42:34                                           initState

**Comment by iifast2** [comment]
**modify_training_page.dart**   Check Validators & Model

**Comment by iifast2** [comment]
## Youtube Video Link null value causing the issue.
